#define MAXNODES 10000
#define MAXNIF 12
#define MAXNOME 51
#define MAXCIDADE 21
#define MAXESTADOCIV 12
#define MAXEMAIL 51
#define MAXUSERSTR 6
#define MAXAPAGADO 2
#define MAXMSG 258
#define MAXTIPOREL 5
#define END 2
#define FAM "fam"
#define AMI "ami"
#define PRO "pro"
