import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main_menu.java
 *
 * Created on 7/Jun/2010, 22:39:27
 */

/**
 *
 * @author miguel
 */
public class Main_menu extends javax.swing.JFrame {
    
    private SoAmigos amigos;

    /** Creates new form Main_menu */
    public Main_menu(SoAmigos amigos) {
        this.amigos = amigos;
        initComponents();
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btConfirmar = new javax.swing.JButton();
        label2 = new java.awt.Label();
        nomelogintxt = new javax.swing.JTextField();
        niflogintxt = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        btConfirmar.setText("Confirmar");
        btConfirmar.setPreferredSize(new java.awt.Dimension(70, 30));
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 2, 0);
        getContentPane().add(btConfirmar, gridBagConstraints);

        label2.setText("NIF:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 2, 0);
        getContentPane().add(label2, gridBagConstraints);

        nomelogintxt.setPreferredSize(new java.awt.Dimension(10, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 2, 0);
        getContentPane().add(nomelogintxt, gridBagConstraints);

        niflogintxt.setPreferredSize(new java.awt.Dimension(10, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 2, 0);
        getContentPane().add(niflogintxt, gridBagConstraints);

        label1.setText("Nome:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 2, 0);
        getContentPane().add(label1, gridBagConstraints);

        jButton2.setText("Cancelar");
        jButton2.setPreferredSize(new java.awt.Dimension(70, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 2, 0);
        getContentPane().add(jButton2, gridBagConstraints);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-398)/2, (screenSize.height-129)/2, 398, 129);
    }// </editor-fold>//GEN-END:initComponents

    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed
        this.niflogintxt.setBackground(Color.white);
        String nome = nomelogintxt.getText();
        String nif = niflogintxt.getText();

        boolean teste = true;
        int i;
        for(i=0;i<nif.length();i++){
            if (!Character.isDigit(nif.charAt(i))) teste = false;
        }

        if (teste && nif.length()<11) {

            while (nif.length()<10) {
            nif = ("0" + nif);
                }
            this.niflogintxt.setText(nif);
            if (this.amigos.login(nome, nif)) {
                new Utilizador_menu(this.amigos,nif).setVisible(true);
                this.dispose();
                JOptionPane.showMessageDialog(null,"Benvindo: " + nome);
                //nomelogintxt.setText(this.amigos.getPerfil(nif).getUtilizador().getNome());
                //this.setVisible(false);
            }
            else {
                JOptionPane.showMessageDialog(null,"Login inexistente!");
                nomelogintxt.setText("");
                niflogintxt.setText("");
            }
        }
        else {
            this.niflogintxt.setBackground(Color.red);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btConfirmarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
                // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_menu(new SoAmigos()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConfirmar;
    private javax.swing.JButton jButton2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JTextField niflogintxt;
    private javax.swing.JTextField nomelogintxt;
    // End of variables declaration//GEN-END:variables

}
