
import java.util.Observable;
import java.util.Observer;
import java.util.StringTokenizer;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pesquisa.java
 *
 * Created on Jun 11, 2010, 4:31:59 PM
 */

/**
 *
 * @author andre
 */
public class pesquisa extends javax.swing.JFrame implements Observer {

    SoAmigos amigos;
    String nifUser;

    /** Creates new form pesquisa */
    public pesquisa(SoAmigos amigos, String nifUser) {
        this.amigos=amigos;
        this.nifUser = nifUser;
        initComponents();
        this.amigos.addObserver(this);

        DefaultListModel model = new DefaultListModel();

        if (this.amigos!=null) {

            for (Perfil p : this.amigos.treeNif.values())
                if (!amigos.pertenceAmigosNome(p.getUtilizador().getNome(), nifUser)) model.addElement(p.getUtilizador().getNome() + " - " + p.getUtilizador().getNif());
            ListPessoas.setModel(model);
    }
        else ListPessoas.setModel(model);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        cbopc = new javax.swing.JComboBox();
        txtUser = new javax.swing.JTextField();
        txtnif = new javax.swing.JTextField();
        txtmorada = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtnome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListPessoas = new javax.swing.JList();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisa");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(650, 450));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        cbopc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nome:", "Nif:" }));
        cbopc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbopcActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        getContentPane().add(cbopc, gridBagConstraints);

        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 113;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 42);
        getContentPane().add(txtUser, gridBagConstraints);

        txtnif.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        getContentPane().add(txtnif, gridBagConstraints);

        txtmorada.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        getContentPane().add(txtmorada, gridBagConstraints);

        jLabel1.setText("Nome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 0, 1);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("Morada");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 12;
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setText("Nif");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        getContentPane().add(jLabel3, gridBagConstraints);

        jButton1.setText("Adicionar amigo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        getContentPane().add(jButton1, gridBagConstraints);

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        getContentPane().add(jButton2, gridBagConstraints);

        txtnome.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 0, 0);
        getContentPane().add(txtnome, gridBagConstraints);

        ListPessoas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListPessoasMouseClicked(evt);
            }
        });
        ListPessoas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListPessoasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ListPessoas);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 64;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 38);
        getContentPane().add(jScrollPane1, gridBagConstraints);
        getContentPane().add(jDesktopPane1, new java.awt.GridBagConstraints());

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-650)/2, (screenSize.height-450)/2, 650, 450);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nif = txtnif.getText();
        JOptionPane.showMessageDialog(null,"Amigo adicionado com sucesso!");
        txtnif.setText("");
        txtnome.setText("");
        txtmorada.setText("");
        this.amigos.addAmigoNif(nifUser, nif);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        new Utilizador_menu(amigos, nifUser).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new Utilizador_menu(amigos, nifUser).setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void ListPessoasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListPessoasMouseClicked
        String pessoa = ListPessoas.getSelectedValue().toString();
        String user;

        if (cbopc.getSelectedItem().toString().equals("Nome:")){
            StringTokenizer corte = new StringTokenizer(pessoa,"-");
            user = corte.nextToken();
            user = user.substring(0, user.length()-1);
            txtnome.setText(amigos.getPerfilNome(user).getUtilizador().getNome());
            txtnif.setText(amigos.getPerfilNome(user).getUtilizador().getNif());
            txtmorada.setText(amigos.getPerfilNome(user).getUtilizador().getMorada());
        }

        if (cbopc.getSelectedItem().toString().equals("Nif:")){
            user = pessoa.substring(0, 10);
            txtnome.setText(amigos.getPerfil(user).getUtilizador().getNome());
            txtnif.setText(amigos.getPerfil(user).getUtilizador().getNif());
            txtmorada.setText(amigos.getPerfil(user).getUtilizador().getMorada());
        }
    }//GEN-LAST:event_ListPessoasMouseClicked

    private void ListPessoasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListPessoasValueChanged
        String pessoa = ListPessoas.getSelectedValue().toString();
        String user;

        if (cbopc.getSelectedItem().toString().equals("Nome:")){
            StringTokenizer corte = new StringTokenizer(pessoa,"-");
            user = corte.nextToken();
            user = user.substring(0, user.length()-1);
            txtnome.setText(amigos.getPerfilNome(user).getUtilizador().getNome());
            txtnif.setText(amigos.getPerfilNome(user).getUtilizador().getNif());
            txtmorada.setText(amigos.getPerfilNome(user).getUtilizador().getMorada());
        }

        if (cbopc.getSelectedItem().toString().equals("Nif:")){
            user = pessoa.substring(0, 10);
            txtnome.setText(amigos.getPerfil(user).getUtilizador().getNome());
            txtnif.setText(amigos.getPerfil(user).getUtilizador().getNif());
            txtmorada.setText(amigos.getPerfil(user).getUtilizador().getMorada());
        }
    }//GEN-LAST:event_ListPessoasValueChanged

    private void cbopcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbopcActionPerformed
        if (cbopc.getSelectedItem().equals("Nif:")) {
            if ((this.amigos)!=null) {

            DefaultListModel model = new DefaultListModel();
            for (Perfil utili : this.amigos.treeNif.values())
                if (!amigos.pertenceAmigosNome(utili.getUtilizador().getNome(), nifUser)) model.addElement(utili.getUtilizador().getNif() + " - " + utili.getUtilizador().getNome());
            ListPessoas.setModel(model);
        }
        else ListPessoas.setModel(new DefaultListModel());
        }

        if (cbopc.getSelectedItem().equals("Nome:")) {
            if ((this.amigos)!=null) {

            DefaultListModel model = new DefaultListModel();
            for (Perfil utili : this.amigos.treeNome.values())
                if (!amigos.pertenceAmigosNome(utili.getUtilizador().getNome(), nifUser)) model.addElement(utili.getUtilizador().getNome() + " - " + utili.getUtilizador().getNif());
            ListPessoas.setModel(model);
        }
        else ListPessoas.setModel(new DefaultListModel());
        }
    }//GEN-LAST:event_cbopcActionPerformed

    private void txtUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyReleased
        Pattern pattern = Pattern.compile(txtUser.getText());
        DefaultListModel model = new DefaultListModel();

        if (cbopc.getSelectedItem().equals("Nome:")) {
            for (Perfil utili : this.amigos.treeNome.values()) {
                Matcher matcher = pattern.matcher(utili.getUtilizador().getNome());
                if (matcher.find()) model.addElement(utili.getUtilizador().getNome() + " - " + utili.getUtilizador().getNif());
            }
        }

        if (cbopc.getSelectedItem().equals("Nif:")) {
            for (Perfil utili : this.amigos.treeNif.values()) {
                Matcher matcher = pattern.matcher(utili.getUtilizador().getNif());
                if (matcher.find()) model.addElement(utili.getUtilizador().getNif() + " - " + utili.getUtilizador().getNome());
            }
        }

        ListPessoas.setModel(model);
    }//GEN-LAST:event_txtUserKeyReleased

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pesquisa(new SoAmigos(), new String()).setVisible(true);
            }
        });
    }

    public void update(Observable observable, Object obj){

        if (cbopc.getSelectedItem().equals("Nif:")) {
            if ((this.amigos)!=null) {

            DefaultListModel model = new DefaultListModel();
            for (Perfil utili : this.amigos.treeNif.values())
                if (!amigos.pertenceAmigosNome(utili.getUtilizador().getNome(), nifUser)) model.addElement(utili.getUtilizador().getNif() + " - " + utili.getUtilizador().getNome());
            ListPessoas.setModel(model);
        }
        else ListPessoas.setModel(new DefaultListModel());
        }

        if (cbopc.getSelectedItem().equals("Nome:")) {
            if ((this.amigos)!=null) {

            DefaultListModel model = new DefaultListModel();
            for (Perfil utili : this.amigos.treeNome.values())
                if (!amigos.pertenceAmigosNome(utili.getUtilizador().getNome(), nifUser)) model.addElement(utili.getUtilizador().getNome() + " - " + utili.getUtilizador().getNif());
            ListPessoas.setModel(model);
        }
        else ListPessoas.setModel(new DefaultListModel());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList ListPessoas;
    private javax.swing.JComboBox cbopc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextField txtmorada;
    private javax.swing.JTextField txtnif;
    private javax.swing.JTextField txtnome;
    // End of variables declaration//GEN-END:variables
}
