/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Utilizador_menu.java
 *
 * Created on 7/Jun/2010, 18:47:50
 */

/**
 *
 * @author miguel
 */
public class Utilizador_menu extends javax.swing.JFrame {

    private SoAmigos amigos;
    private String nifUser;

    /** Creates new form Utilizador_menu */
    public Utilizador_menu(SoAmigos amigos, String nif) {
        this.amigos=amigos;
        this.nifUser = nif;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btenviar = new javax.swing.JButton();
        btdados = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btveramigos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu Utilizador");
        setFocusableWindowState(false);
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(650, 450));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        btenviar.setText("Mensagens");
        btenviar.setPreferredSize(new java.awt.Dimension(120, 40));
        btenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btenviarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 0);
        getContentPane().add(btenviar, gridBagConstraints);

        btdados.setText("Dados Pessoais");
        btdados.setPreferredSize(new java.awt.Dimension(120, 40));
        btdados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdadosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 0);
        getContentPane().add(btdados, gridBagConstraints);

        jButton4.setText("Sair");
        jButton4.setPreferredSize(new java.awt.Dimension(120, 40));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(36, 0, 0, 0);
        getContentPane().add(jButton4, gridBagConstraints);

        btveramigos.setText("Amigos");
        btveramigos.setPreferredSize(new java.awt.Dimension(120, 40));
        btveramigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btveramigosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.insets = new java.awt.Insets(32, 0, 0, 0);
        getContentPane().add(btveramigos, gridBagConstraints);

        jButton1.setText("Pesquisa");
        jButton1.setPreferredSize(new java.awt.Dimension(120, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 0, 0, 0);
        getContentPane().add(jButton1, gridBagConstraints);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-650)/2, (screenSize.height-450)/2, 650, 450);
    }// </editor-fold>//GEN-END:initComponents

    private void btenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btenviarActionPerformed
        new Mensagens(amigos, nifUser).setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btenviarActionPerformed

    private void btdadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdadosActionPerformed
        new Dados_pessoais(amigos, nifUser).setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btdadosActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();                 // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btveramigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btveramigosActionPerformed
        new ver_amigos(amigos, nifUser).setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btveramigosActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
               // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new pesquisa(amigos, nifUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Utilizador_menu(new SoAmigos(), new String()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btdados;
    private javax.swing.JButton btenviar;
    private javax.swing.JButton btveramigos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables

}
