
import java.util.Observable;
import java.util.Observer;
import java.util.StringTokenizer;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ver_amigos.java
 *
 * Created on 7/Jun/2010, 18:30:15
 */

/**
 *
 * @author miguel
 */
public class ver_amigos extends javax.swing.JFrame implements Observer {

    private SoAmigos amigos;
    private String nifUser;
    private String nome;

    /** Creates new form ver_amigos */
    public ver_amigos(SoAmigos amigos, String nifUser) {
        this.amigos=amigos;
        this.nifUser=nifUser;
        initComponents();
        this.amigos.addObserver(this);
        
        int i = 0;

        DefaultListModel model = new DefaultListModel();

        if ((this.amigos.getPerfil(this.nifUser).getAmigosP())!=null) {

            for (String nif : this.amigos.verAmigos(nifUser).keySet())
                model.addElement(amigos.getPerfil(nif).getUtilizador().getNome());
            ListAmigos.setModel(model);
    }
        else ListAmigos.setModel(model);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        btRemover = new javax.swing.JButton();
        btEnviar = new javax.swing.JButton();
        nometxt = new javax.swing.JTextField();
        moradatxt = new javax.swing.JTextField();
        niftxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtamigo = new javax.swing.JTextField();
        btAdicionar = new javax.swing.JButton();
        cbopc = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListAmigos = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Amigos");
        setMinimumSize(new java.awt.Dimension(650, 450));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        label1.setText("Nome:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        getContentPane().add(label1, gridBagConstraints);

        label2.setText("Morada");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        getContentPane().add(label2, gridBagConstraints);

        label3.setText("NIF:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        getContentPane().add(label3, gridBagConstraints);

        btRemover.setText("Remover");
        btRemover.setEnabled(false);
        btRemover.setPreferredSize(new java.awt.Dimension(70, 30));
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 50);
        getContentPane().add(btRemover, gridBagConstraints);

        btEnviar.setText("Enviar mensagem");
        btEnviar.setEnabled(false);
        btEnviar.setMaximumSize(new java.awt.Dimension(69, 29));
        btEnviar.setMinimumSize(new java.awt.Dimension(69, 29));
        btEnviar.setPreferredSize(new java.awt.Dimension(70, 30));
        btEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 50);
        getContentPane().add(btEnviar, gridBagConstraints);

        nometxt.setEditable(false);
        nometxt.setPreferredSize(new java.awt.Dimension(10, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(nometxt, gridBagConstraints);

        moradatxt.setEditable(false);
        moradatxt.setPreferredSize(new java.awt.Dimension(10, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 165;
        getContentPane().add(moradatxt, gridBagConstraints);

        niftxt.setEditable(false);
        niftxt.setPreferredSize(new java.awt.Dimension(10, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        getContentPane().add(niftxt, gridBagConstraints);

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 50);
        getContentPane().add(jButton1, gridBagConstraints);

        txtamigo.setPreferredSize(new java.awt.Dimension(10, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 64;
        getContentPane().add(txtamigo, gridBagConstraints);

        btAdicionar.setText("Adicionar");
        btAdicionar.setPreferredSize(new java.awt.Dimension(70, 30));
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 50);
        getContentPane().add(btAdicionar, gridBagConstraints);

        cbopc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nome", "Nif" }));
        cbopc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbopcActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        getContentPane().add(cbopc, gridBagConstraints);

        ListAmigos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "1" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        ListAmigos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListAmigosMouseClicked(evt);
            }
        });
        ListAmigos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListAmigosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ListAmigos);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 160;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 2);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-650)/2, (screenSize.height-450)/2, 650, 450);
    }// </editor-fold>//GEN-END:initComponents

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        int num = ListAmigos.getSelectedValue().toString().length();
        String nome = ListAmigos.getSelectedValue().toString().substring(0, num);

        nometxt.setText("");
        niftxt.setText("");
        moradatxt.setText("");
        btRemover.setEnabled(false);
        btEnviar.setEnabled(false);
        this.amigos.removerAmigoNome(nome,amigos.getPerfil(nifUser).getUtilizador().getNome());
        // TODO add your handling code here:
    }//GEN-LAST:event_btRemoverActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new Utilizador_menu(amigos, nifUser).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void btEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnviarActionPerformed
        this.dispose();
        new Env_Mensagem(amigos,nifUser,nome).setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btEnviarActionPerformed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        String amigo = txtamigo.getText();
        String opc = cbopc.getSelectedItem().toString();

        if (opc.equals("Nif")) {

            while (amigo.length()<10) {
            amigo = ("0" + amigo);
                }

            if (amigos.getPerfil(amigo)!=null) {
                if (amigos.getPerfil(nifUser).pertenceAmigos(amigo)==false) {
                amigos.addAmigoNif(amigos.getPerfil(nifUser).getUtilizador().getNif(), amigo);
                JOptionPane.showMessageDialog(null,"Amigos adicionado com sucesso!");
                }
                else JOptionPane.showMessageDialog(null,"Já são amigos!");
            }
            else JOptionPane.showMessageDialog(null,"Nif enixistente!");
        }

        if (opc.equals("Nome")) {
            if (amigos.getPerfilNome(amigo)!=null) {
                if (amigos.pertenceAmigosNome(amigo, nifUser)==false) {
                amigos.addAmigoNome(amigos.getPerfil(nifUser).getUtilizador().getNome(), amigo);
                JOptionPane.showMessageDialog(null,"Amigos adicionado com sucesso!");
                }
                else JOptionPane.showMessageDialog(null,"Já são amigos!");
            }
            else JOptionPane.showMessageDialog(null,"Nome enixistente!");
        }

        txtamigo.setText("");
        

        // TODO add your handling code here:
}//GEN-LAST:event_btAdicionarActionPerformed

    private void cbopcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbopcActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cbopcActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new Utilizador_menu(amigos, nifUser).setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ListAmigosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListAmigosMouseClicked
        String pessoa = ListAmigos.getSelectedValue().toString();
        //String user;

        nometxt.setText(amigos.getPerfilNome(pessoa).getUtilizador().getNome());
        niftxt.setText(amigos.getPerfilNome(pessoa).getUtilizador().getNif());
        moradatxt.setText(amigos.getPerfilNome(pessoa).getUtilizador().getMorada());
        btRemover.setEnabled(true);
        btEnviar.setEnabled(true);

        // TODO add your handling code here:
}//GEN-LAST:event_ListAmigosMouseClicked

    private void ListAmigosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListAmigosValueChanged
        String pessoa = ListAmigos.getSelectedValue().toString();
        String user;

        if (cbopc.getSelectedItem().toString().equals("Nome:")){
            StringTokenizer corte = new StringTokenizer(pessoa,"-");
            user = corte.nextToken();
            user = user.substring(0, user.length()-1);
            nometxt.setText(amigos.getPerfilNome(user).getUtilizador().getNome());
            niftxt.setText(amigos.getPerfilNome(user).getUtilizador().getNif());
            moradatxt.setText(amigos.getPerfilNome(user).getUtilizador().getMorada());
        }

        if (cbopc.getSelectedItem().toString().equals("Nif:")){
            user = pessoa.substring(0, 10);
            nometxt.setText(amigos.getPerfil(user).getUtilizador().getNome());
            niftxt.setText(amigos.getPerfil(user).getUtilizador().getNif());
            moradatxt.setText(amigos.getPerfil(user).getUtilizador().getMorada());
        }
}//GEN-LAST:event_ListAmigosValueChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ver_amigos(new SoAmigos(), new String()).setVisible(true);
            }
        });
    }

    public void update(Observable observable, Object obj){
        
        if ((this.amigos.getPerfil(this.nifUser).getAmigosP())!=null) {

            DefaultListModel model = new DefaultListModel();
            for (String nif : this.amigos.verAmigos(nifUser).keySet())
                model.addElement(amigos.getPerfil(nif).getUtilizador().getNome());
            ListAmigos.setModel(model);
        }
        else ListAmigos.setModel(new DefaultListModel());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList ListAmigos;
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btEnviar;
    private javax.swing.JButton btRemover;
    private javax.swing.JComboBox cbopc;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JTextField moradatxt;
    private javax.swing.JTextField niftxt;
    private javax.swing.JTextField nometxt;
    private javax.swing.JTextField txtamigo;
    // End of variables declaration//GEN-END:variables

}
